language: node_js

node_js:
  - "12"
  - "node"

sudo: false

cache:
    npm: false
    directories:
        - $HOME/.npm

before_install:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then npm update -g npm; fi
  - if [[ "$TRAVIS_OS_NAME" = "windows" ]]; then node `npm prefix -g`/node_modules/npm/bin/npm-cli.js i -g npm@latest; fi

install:
  - "npm install"

os:
  - "linux"
  - "osx"
  - "windows"

matrix:
    include:
        -   node_js: "node"
            os: "linux"
            name: "Browser tests"
            addons:
                chrome: stable
            install: "npm install && cd browser && npm install"
            script: "pwd && npm test"
